
.PHONY: always
always:
	g++ test.cxx -I /home/kpfalzer/projects/laol/c++/laolrt -I /home/kpfalzer/projects/xyzzy/src -o ./test -g /home/kpfalzer/projects/laol/c++/dist/debug/linux/laolrt.a /home/kpfalzer/projects/xyzzy/dist/debug/linux/xyzzy.a
